### ISSUE TITLE
Execution fails

### ISSUE THREAD

**Issue by JoshuaDoornik** [Azure-Samples/consumption-cost-node#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy from Azure-Samples
> make request https://costcontrolfunction.azurewebsites.net/api/download-consumtion-cost?code=<my code>
with JSON body '{"filter":"[resourcegroup]","detailed":"true"}'

### Any log messages given by the failure
{
    "id": "d427fe1d-a5ed-454d-a47c-5a89c5f1c03d",
    "requestId": "c54a8670-1f78-4112-ad88-243ce1c16734",
    "statusCode": 500,
    "errorCode": 0,
    "message": "Exception while executing function: Functions.download-consumtion-cost -> One or more errors occurred. -> Error: Cannot find module 'ms-rest-azure'\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (C:\\home\\site\\wwwroot\\common\\commerceUtils.js:1:83)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)"
}

### Expected/desired behavior
>  The response as described in the documents, 
{ total: (Number, the total cost), details: (Key-Value pairs of resource and cost)}

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Tried on windows 10 with Postman
Ubuntu WSL

### Versions
> Pulled from master branch

**Comment by jgezelscorp** [comment]
Same here.
